import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Toolbar from '../components/Toolbar';
import VisualView from '../components/VisualView';

import { BlockContextProvider } from '../contexts/blockContext';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">Hassuu Editor!</a>
        </h1>

        <BlockContextProvider>
          <div className="wysiwyg-next">
            <Toolbar />
            <div className="content-area">
              <VisualView />
              <textarea className="html-view"></textarea>
            </div>
          </div>
        </BlockContextProvider>

        {/* modal */}
      </main>
    </div>
  );
}
